insert into Tag (value, count) values 
('Social movements', 14),
('Billiards', 30),
('Classic rock', 48),
('Geography', 30),
('Information security', 35),
('Musical instruments', 55),
('Chefs', 58),
('Football', 31),
('Fields of study', 23),
('NCAA Men’s Basketball', 88),
('World music', 91),
('Business & finance news', 3),
('Dance', 53),
('Destinations', 84),
('Martial arts', 53),
('Gymnastics', 77),
('Dance music', 84),
('Tech personalities', 79),
('Transportation', 80),
('COVID-19', 89),
('Triathlon', 47),
('arts & culture', 10),
('Drone technology', 51),
('Chemistry', 56),
('Tech news', 38),
('Nonprofits', 62),
('Golf', 63),
('NCAA Women’s Basketball', 38),
('food Food', 65),
('NCAA Women’s Basketball', 38),
('Gaming news', 97),
('Opera', 30),
('Local news', 42),
('Destinations', 72),
('Marketing', 95),
('Alternative', 6),
('Astrology', 58),
('Business travel', 55),
('Tabletop gaming', 61),
('Business travel', 48),
('Marketing', 19),
('Soft rock', 19),
('Music news', 68),
('Australian rules football', 48),
('K-hip hop', 66),
('FinTech', 48),
('Volleyball', 63),
('Dance', 50),
('Musical instruments', 96),
('Folk Music', 79),
('Cricket', 56),
('Alternative', 1),
('Winter sports', 80),
('Radio stations', 33),
('hobbies & interests Animals', 5),
('movies and tv Movies', 24),
('Business travel', 23),
('Sports icons', 83),
('FinTech', 17),
('Tech news', 24),
('Geography', 100),
('Celebrities', 37),
('Tech personalities', 17),
('Tech news', 73),
('Business travel', 1),
('news Arts and culture news', 96),
('Cloud platforms', 83),
('Cryptocurrencies', 56),
('Fantasy sports', 46),
('Transportation', 52),
('Surfing', 79),
('Golf', 52),
('Gaming news', 50),
('Anime', 95),
('fashion & beauty Beauty', 6),
('Social movements', 87),
('Destinations', 37),
('Sports news', 62),
('Business travel', 91),
('Art', 97),
('Hunting', 34),
('Baseball', 45),
('Tech brands', 13),
('Cruises', 94),
('Gaming personalities & esports players', 79),
('C-pop', 80),
('Pop', 57),
('Hockey', 16),
('Basketball', 56),
('Internet of things', 1),
('Australian Football League', 37),
('Classical music', 60),
('Archaeology', 10),
('news Arts and culture news', 82),
('Investing', 2),
('Theme parks', 10),
('Sports icons', 79),
('Education', 80),
('Classical music', 84),
('Classical music', 87),
('Netball', 70),
('Archaeology', 61),
('At home', 99),
('Augmented reality', 90),
('gaming Gaming', 30),
('Music news', 1),
('Digital creators', 76),
('Metal', 29),
('Databases', 52),
('Rowing', 40),
('Tech personalities', 79),
('Fitness', 92),
('fashion & beauty Beauty', 51),
('gaming Gaming', 51),
('Rock climbing', 49),
('Soft rock', 30),
('Drone technology', 32),
('Health news', 47),
('Digital creators', 41),
('Physics', 38),
('Drone technology', 97),
('Data science', 37),
('C-pop', 14),
('Cryptocurrencies', 77),
('Unexplained phenomena', 42),
('sports Sports', 82),
('Basketball', 46),
('Popular franchises', 90),
('Nonprofits', 100),
('Marketing', 31),
('movies and tv Movies', 43),
('Luxury travel', 2),
('Sports news', 15),
('Music brands', 33),
('Esports', 92),
('Geography', 70),
('Hunting', 27),
('Destinations', 100),
('Books', 34),
('Cricket', 45),
('NASCAR', 72),
('K-pop', 83),
('MLB', 79),
('At home', 19),
('travel Travel', 8),
('Chemistry', 19),
('US national news', 68),
('Tabletop gaming', 71),
('Entertainment brands', 54),
('Tennis', 5),
('FinTech', 36),
('Hip-hop & rap', 79),
('Jazz', 50),
('fashion & beauty Beauty', 38),
('Sports icons', 25),
('Rowing', 86),
('Startups', 4),
('food Food', 65),
('Movie news', 20),
('Tech news', 17),
('Rodeo', 83),
('IndyCar', 10),
('Information security', 25),
('Billiards', 4),
('Hip-hop & rap', 80),
('NASCAR', 11),
('Business & finance news', 13),
('Blues', 62),
('Tech news', 79),
('Combat Sports', 20),
('business & finance Business & finance', 8),
('Horse racing & equestrian', 93),
('Darts', 53),
('Classical music', 33),
('Softball', 73),
('Rodeo', 84),
('Transportation', 16),
('Soft rock', 69),
('Fields of study', 80),
('Information security', 70),
('Local news', 70),
('Lacrosse', 82),
('Advertising', 71),
('Sailing', 17),
('Theater', 85),
('Musical instruments', 47),
('Fitness', 77),
('Cooking', 57),
('Golf', 55),
('Billiards', 16),
('Game developers & publishers', 96),
('Anime', 27),
('Winter sports', 83),
('Softball', 48),
('WNBA', 94),
('Combat Sports', 90),
('Cruises', 67),
('Theater', 59),
('Cloud platforms', 74),
('Databases', 92),
('Auto racing', 95),
('Rowing', 89),
('Winter sports', 49),
('Dance music', 92),
('Video games', 48),
('Art', 94),
('Punk', 59),
('Education', 60),
('Blues', 27),
('Punk', 74),
('entertainment Entertainment', 87),
('movies and tv Movies', 75),
('Tech news', 37),
('Indie spotlight', 17),
('Conservation & environmentalism', 90),
('Gymnastics', 49),
('Air travel', 6),
('science Science', 13),
('Gaming news', 32),
('Rugby', 21),
('Destinations', 10),
('Track & field', 78),
('Cryptocurrencies', 48),
('Family', 28),
('Popular franchises', 94),
('Billiards', 34),
('Investing', 35),
('Marketing', 32),
('Information security', 63),
('Advertising', 52),
('Table tennis', 69),
('Chefs', 6),
('Bollywood music', 9),
('Collectibles', 64),
('Theme parks', 75),
('Sports news', 35),
('Table tennis', 38),
('technology Technology', 19),
('Destinations', 45),
('Drone technology', 4),
('Surfing', 56),
('Music news', 53),
('Combat Sports', 11),
('Cruises', 38),
('Esports', 28),
('Marketing', 62),
('Cheerleading', 24),
('Blues', 43),
('Classic rock', 61),
('Movie news', 40),
('Baseball', 76),
('Sports icons', 34),
('Science news', 2),
('Unexplained phenomena', 36),
('Blues', 30),
('Data science', 40),
('Computer programming', 2),
('Opera', 54),
('Business & finance news', 16),
('Australian rules football', 56),
('Experimental music', 73),
('Radio stations', 91),
('food Food', 73),
('Cryptocurrencies', 75),
('Cloud computing', 12),
('Destinations', 72),
('science Science', 4),
('Soccer', 83),
('Auto racing', 46),
('Cloud platforms', 73),
('hobbies & interests Animals', 89),
('Fields of study', 49),
('Soft rock', 69),
('Horse racing & equestrian', 11),
('Fashion', 89),
('National parks', 8),
('Triathlon', 62),
('Family', 75),
('Tech personalities', 59),
('Music news', 98),
('Books', 28),
('Australian Football League', 63),
('Archaeology', 29),
('Drone racing', 97),
('Chemistry', 57),
('Punk', 45),
('Tabletop gaming', 20),
('Pop', 43),
('Australian rules football', 6),
('J-pop', 94),
('Classic rock', 51),
('Science news', 50),
('Local news', 52),
('fashion & beauty Beauty', 61),
('outdoors Birdwatching', 97),
('Conservation & environmentalism', 83),
('Metal', 28),
('Jazz', 73),
('Nature', 62),
('Nature', 33),
('Game developers & publishers', 16),
('R&B and soul', 3),
('Sports news', 43),
('Museums and institutions', 72),
('Marketing', 58),
('Luxury travel', 30),
('Netball', 38),
('NCAA Women’s Basketball', 92),
('Tech personalities', 52),
('Family', 98),
('Geography', 91),
('Business & finance news', 5),
('Sports journalists & coaches', 71),
('outdoors Birdwatching', 86),
('Science news', 42),
('gaming Gaming', 46),
('Podcasts', 4),
('Business & finance news', 61),
('Classic rock', 28),
('Writing', 44),
('Netball', 8),
('Travel guides', 48),
('Databases', 64),
('Cloud platforms', 5),
('Track & field', 39),
('Fantasy sports', 59),
('Basketball', 49),
('sports Sports', 82),
('Biology', 8),
('Tech news', 35),
('Geography', 72),
('Jazz', 52),
('movies and tv Movies', 12),
('business & finance Business & finance', 86),
('NASCAR', 30),
('Classic rock', 23),
('WNBA', 64),
('entertainment Entertainment', 56),
('Gaming personalities & esports players', 8),
('careers Accounting', 14),
('Music news', 38),
('Esports', 73),
('Chefs', 55),
('Fantasy sports', 21),
('outdoors Birdwatching', 82),
('Small business', 79),
('Fashion', 5),
('Game developers & publishers', 63),
('Country music', 52),
('Destinations', 56),
('Archaeology', 74),
('Information security', 44),
('Business & finance news', 35),
('Digital creators', 49),
('Television', 13),
('Blues', 23),
('Bollywood music', 26),
('Information security', 59),
('Business professions', 97),
('Horse racing & equestrian', 73),
('Collectibles', 40),
('technology Technology', 75),
('Punjabi music', 23),
('Transportation', 92),
('Gaming news', 25),
('Rowing', 67),
('Pop', 50),
('Tech personalities', 55),
('Computer programming', 51),
('Combat Sports', 45),
('Tennis', 70),
('Football', 58),
('Cycling', 85),
('Advertising', 52),
('Databases', 37),
('Biology', 88),
('travel Travel', 92),
('Lacrosse', 6),
('Golf', 26),
('NBA', 86),
('Augmented reality', 31),
('Conservation & environmentalism', 89),
('Cloud computing', 48),
('Sports news', 5),
('Alternative', 44),
('food Food', 15),
('Tennis', 80),
('Music news', 89),
('Health news', 67),
('Tech personalities', 43),
('Cheerleading', 2),
('Horoscope', 68),
('Folk Music', 19),
('Sports journalists & coaches', 13),
('Popular franchises', 86),
('Hockey', 74),
('Nature', 11),
('Internet of things', 27),
('Hunting', 12),
('travel Travel', 9),
('Musical instruments', 61),
('Podcasts', 100),
('entertainment Entertainment', 89),
('Volleyball', 45),
('Skateboarding', 79),
('Books', 18),
('Rugby', 81),
('FinTech', 81),
('Swimming', 87),
('Weather', 11),
('Fashion', 72),
('Australian rules football', 32),
('Music news', 92),
('technology Technology', 19),
('Reggaeton', 75),
('FinTech', 7),
('Classical music', 12),
('Sailing', 6),
('Auto racing', 38),
('Musical instruments', 8),
('Hockey', 36),
('movies and tv Movies', 83),
('Motorcycle racing', 33),
('Cruises', 18),
('Cricket', 94),
('Data science', 10),
('Video games', 46),
('Blues', 45),
('Internet of things', 92),
('Gaming personalities & esports players', 85),
('Art', 90),
('Space & astronomy', 70),
('Table tennis', 88),
('Fields of study', 13),
('FinTech', 41),
('Soft rock', 53),
('science Science', 56),
('J-pop', 93),
('Drone technology', 67),
('Alternative', 69),
('Radio stations', 59),
('Rowing', 3),
('Augmented reality', 97),
('travel Travel', 96),
('Fitness', 11),
('science Science', 81),
('business & finance Business & finance', 15),
('Social movements', 23),
('Lacrosse', 63),
('science Science', 85),
('gaming Gaming', 55),
('Podcasts', 9),
('hobbies & interests Animals', 95),
('Sports icons', 57),
('Music brands', 35),
('Internet of things', 44),
('NCAA Women’s Basketball', 48),
('Travel guides', 56),
('Astrology', 47),
('Surfing', 18),
('Tech personalities', 59),
('Books', 71),
('NCAA Women’s Basketball', 5),
('FinTech', 95),
('Music festivals', 77),
('Theme parks', 13),
('Tech brands', 22),
('Small business', 48),
('Fashion', 88),
('US national news', 51),
('Australian rules football', 99),
('Table tennis', 42),
('Geology', 60),
('Internet of things', 98),
('Reggaeton', 43),
('Education', 21),
('business & finance Business & finance', 22),
('Baseball', 5),
('Investing', 85),
('Pop', 48),
('IndyCar', 91),
('Air travel', 44),
('Jazz', 36),
('At home', 47),
('Business travel', 70),
('Chemistry', 39),
('Alternative', 30),
('R&B and soul', 87),
('Sci-fi and fantasy', 27),
('Sports journalists & coaches', 98),
('hobbies & interests Animals', 51),
('Tech news', 27),
('Combat Sports', 23),
('Luxury travel', 11),
('Geography', 40),
('Skateboarding', 55),
('Entertainment brands', 11),
('news Arts and culture news', 65),
('COVID-19', 25),
('Australian Football League', 16),
('technology Technology', 81),
('WNBA', 38),
('Punjabi music', 71),
('Indie spotlight', 91),
('gaming Gaming', 6),
('Horoscope', 67),
('Popular franchises', 67),
('travel Travel', 79),
('Science news', 16),
('Fashion', 39),
('Swimming', 36),
('Cooking', 79),
('Art', 16),
('Football', 98),
('Folk Music', 28),
('Table tennis', 32),
('Formula 1', 31),
('technology Technology', 56),
('NCAA Men’s Basketball', 1),
('Geology', 33),
('Entertainment brands', 15),
('FinTech', 74),
('science Science', 60),
('Science news', 28),
('Soft rock', 6),
('Sports news', 64),
('Science news', 27),
('careers Accounting', 82),
('Business & finance news', 94),
('Indie spotlight', 91),
('Biology', 28),
('Winter sports', 26),
('Video game platforms & hardware', 76),
('Soft rock', 90),
('Dance music', 89),
('NCAA Men’s Basketball', 73),
('gaming Gaming', 47),
('Music news', 41),
('Fitness', 42),
('FinTech', 13),
('Winter sports', 10),
('Australian rules football', 39),
('Comics', 17),
('Sci-fi and fantasy', 12),
('Triathlon', 26),
('Rowing', 85),
('Football', 98),
('Auto racing', 100),
('Venture capital', 40),
('Sports news', 2),
('travel Travel', 59),
('Reggaeton', 39),
('Space & astronomy', 78),
('Family', 7),
('Table tennis', 1),
('J-pop', 50),
('Reggaeton', 85),
('FinTech', 19),
('Small business', 11),
('Australian rules football', 95),
('US national news', 61),
('COVID-19', 17),
('Rock climbing', 59),
('NCAA Women’s Basketball', 100),
('Business & finance news', 75),
('Travel guides', 81),
('Horse racing & equestrian', 24),
('Pop', 32),
('Health news', 71),
('Destinations', 51),
('Gaming personalities & esports players', 50),
('Data science', 27),
('food Food', 3),
('Business travel', 51),
('Cryptocurrencies', 24),
('Horse racing & equestrian', 92),
('IndyCar', 61),
('Netball', 59),
('Horoscope', 97),
('Baseball', 54),
('news Arts and culture news', 85),
('Music news', 81),
('COVID-19', 77),
('K-pop', 14),
('Theater', 67),
('Bollywood music', 94),
('Formula 1', 29),
('Pop', 20),
('Conservation & environmentalism', 46),
('gaming Gaming', 85),
('Science news', 13),
('Fishing', 34),
('Rowing', 20),
('Theme parks', 15),
('Australian rules football', 39),
('Cooking', 43),
('Podcasts', 92),
('Books', 63),
('Darts', 49),
('Chemistry', 5),
('World music', 18),
('R&B and soul', 44),
('Computer programming', 66),
('outdoors Birdwatching', 17),
('NASCAR', 80),
('Art', 38),
('Fashion', 90),
('Folk Music', 92),
('Softball', 19),
('Geography', 63),
('Australian Football League', 34),
('Geography', 56),
('FinTech', 6),
('Podcasts', 80),
('hobbies & interests Animals', 11),
('K-pop', 61),
('Classical music', 12),
('arts & culture', 97),
('Geography', 83),
('arts & culture', 100),
('Movie news', 72),
('R&B and soul', 17),
('FinTech', 85),
('Fishing', 42),
('NCAA Men’s Basketball', 81),
('Fields of study', 37),
('Fields of study', 85),
('Art', 5),
('Sci-fi and fantasy', 13),
('WNBA', 20),
('Music festivals', 75),
('hobbies & interests Animals', 46),
('Music news', 100),
('FinTech', 31),
('Advertising', 33),
('Swimming', 65),
('Virtual reality', 71),
('Science news', 97),
('Chefs', 56),
('WNBA', 93),
('Tabletop gaming', 37),
('Electronic music', 19),
('Geology', 2),
('Golf', 98),
('Biology', 79),
('FinTech', 40),
('Gaming personalities & esports players', 4),
('Cryptocurrencies', 3),
('Netball', 75),
('J-pop', 72),
('Drone racing', 92),
('Small business', 66),
('Nonprofits', 51),
('Geology', 29),
('Tech news', 2),
('Swimming', 30),
('Databases', 26),
('Track & field', 79),
('World news', 14),
('Rodeo', 90),
('Drone technology', 33),
('Soccer', 28),
('Folk Music', 75),
('NASCAR', 60),
('Theme parks', 36),
('arts & culture', 47),
('Computer programming', 42),
('Business & finance news', 37),
('K-hip hop', 8),
('Business & finance news', 11),
('fashion & beauty Beauty', 81),
('Tech news', 34),
('Weather', 88),
('Nonprofits', 18),
('Punk', 73),
('Fishing', 26),
('NCAA Men’s Basketball', 78),
('Travel guides', 58),
('Fields of study', 73),
('Blues', 82),
('Surfing', 11),
('Gaming news', 3),
('Science news', 62),
('Baseball', 64),
('food Food', 42),
('Fitness', 72),
('gaming Gaming', 87),
('Tech personalities', 26),
('Cricket', 10),
('Cruises', 73),
('World music', 90),
('Tennis', 12),
('Weather', 59),
('Celebrities', 22),
('Australian rules football', 35),
('Australian Football League', 35),
('Databases', 77),
('Augmented reality', 54),
('COVID-19', 4),
('C-pop', 84),
('Combat Sports', 80),
('Venture capital', 11),
('food Food', 82),
('Museums and institutions', 13),
('Baseball', 80),
('Weather', 73),
('C-pop', 77),
('Bollywood music', 89),
('Experimental music', 86),
('Punjabi music', 23),
('Reggaeton', 64),
('Chemistry', 74),
('Horse racing & equestrian', 91),
('Adventure travel', 52),
('Animation', 50),
('Business travel', 62),
('Tennis', 42),
('Business professions', 36),
('Esports', 88),
('science Science', 39),
('COVID-19', 8),
('Tabletop gaming', 62),
('Business personalities', 94),
('Blues', 67),
('Luxury travel', 57),
('Sports journalists & coaches', 31),
('Cycling', 11),
('Space & astronomy', 35),
('Musical instruments', 48),
('Nonprofits', 7),
('Folk Music', 85),
('news Arts and culture news', 35),
('Cooking', 40),
('Tech news', 52),
('Football', 16),
('J-pop', 30),
('COVID-19', 11),
('Video games', 28),
('arts & culture', 14),
('Sci-fi and fantasy', 22),
('Destinations', 34),
('Australian rules football', 47),
('COVID-19', 71),
('Rock climbing', 32),
('Information security', 54),
('Fitness', 7),
('Rodeo', 62),
('Blues', 68),
('Rock climbing', 86),
('Databases', 36),
('Electronic music', 59),
('Lacrosse', 15),
('Dance', 26),
('Startups', 64),
('Electronic music', 23),
('Virtual reality', 1),
('Volleyball', 88),
('Geography', 35),
('Digital creators', 3),
('Astrology', 5),
('World music', 83),
('Sports news', 49),
('Billiards', 88),
('Unexplained phenomena', 2),
('Basketball', 77),
('Blues', 100),
('Darts', 70),
('Handball', 31),
('Darts', 72),
('fashion & beauty Beauty', 39),
('Sports icons', 3),
('Science news', 19),
('Cycling', 1),
('Gaming personalities & esports players', 54),
('Geography', 75),
('Cricket', 36),
('Virtual reality', 22),
('Sports news', 34),
('Local news', 67),
('J-pop', 77),
('COVID-19', 76),
('Tech personalities', 77),
('Computer programming', 51),
('FinTech', 43),
('Digital creators', 16),
('Theater', 62),
('World news', 33),
('Australian rules football', 50),
('Animation', 87),
('Conservation & environmentalism', 51),
('Swimming', 98),
('Nonprofits', 42),
('Popular franchises', 84),
('Chemistry', 32),
('Sci-fi and fantasy', 100),
('US national news', 55),
('Jazz', 60),
('Fitness', 34),
('outdoors Birdwatching', 75),
('Information security', 56),
('Cheerleading', 57),
('Video game platforms & hardware', 43),
('Bollywood music', 29),
('Marketing', 91),
('Bollywood music', 7),
('Business & finance news', 71),
('Punjabi music', 100),
('Geography', 6),
('Rock', 92),
('Gaming personalities & esports players', 26),
('Billiards', 78),
('Conservation & environmentalism', 8),
('Horoscope', 61),
('Science news', 46),
('K-pop', 49),
('Music news', 52),
('Art', 19),
('Small business', 75),
('Electronic music', 15),
('Health news', 11),
('Movie news', 12),
('Transportation', 17),
('Cooking', 86),
('Triathlon', 70),
('Esports', 83),
('Television', 32),
('Investing', 43),
('Data science', 10),
('Reggaeton', 29),
('Sports news', 21),
('Comedy', 90),
('Science news', 37),
('Business travel', 46),
('Tennis', 34),
('Computer programming', 24),
('Virtual reality', 51),
('Cycling', 4),
('K-hip hop', 92),
('Music festivals', 70),
('Drone technology', 46),
('Virtual reality', 9),
('Social movements', 87),
('Biology', 97),
('Hockey', 98),
('Sci-fi and fantasy', 47),
('Science news', 60),
('Baseball', 87),
('hobbies & interests Animals', 65),
('Fantasy sports', 5),
('Chefs', 99),
('Health news', 4),
('Popular franchises', 32),
('Business travel', 6),
('Indie spotlight', 55),
('Biology', 32),
('Tech personalities', 53),
('Volleyball', 2),
('J-pop', 12),
('Adventure travel', 98),
('Rodeo', 31),
('Sports icons', 86),
('Art', 36),
('Transportation', 98),
('Combat Sports', 98),
('Video game platforms & hardware', 100),
('J-pop', 23),
('Startups', 46),
('Books', 54),
('Table tennis', 8),
('Science news', 88),
('Australian rules football', 43),
('Lacrosse', 6),
('Surfing', 34),
('Surfing', 42),
('Darts', 51),
('business & finance Business & finance', 25),
('Dance', 2),
('Cricket', 5),
('Comics', 30),
('Weather', 67),
('Physics', 24),
('Experimental music', 58),
('Classical music', 100),
('Sci-fi and fantasy', 75),
('Opera', 3),
('Cooking', 21),
('Music festivals', 45),
('Basketball', 13),
('hobbies & interests Animals', 86),
('Local news', 80),
('Metal', 11),
('Drone technology', 74),
('Video games', 42),
('NASCAR', 50),
('fashion & beauty Beauty', 11),
('Punk', 15),
('World music', 86),
('Comics', 97),
('Punk', 86),
('careers Accounting', 16),
('Business personalities', 49),
('Science news', 53),
('Soft rock', 82),
('Combat Sports', 45),
('Sports icons', 45),
('Australian Football League', 97),
('FinTech', 24),
('Weather', 77),
('Theme parks', 77),
('Comics', 50),
('Animation', 39),
('Soft rock', 38),
('Horse racing & equestrian', 100),
('Swimming', 19),
('Tech news', 75),
('hobbies & interests Animals', 17),
('Soccer', 17),
('Anime', 41),
('Cycling', 63),
('Soft rock', 12),
('Handball', 75),
('Fitness', 1),
('Local news', 73),
('World news', 78),
('Gymnastics', 73),
('Australian rules football', 65),
('Bollywood music', 52),
('Startups', 11),
('Bollywood music', 70),
('Softball', 26),
('Geology', 85),
('WNBA', 87),
('Archaeology', 46),
('Rugby', 21),
('Cloud computing', 51),
('Sports journalists & coaches', 51),
('Fitness', 88),
('Jazz', 99),
('hobbies & interests Animals', 29),
('Computer programming', 42),
('Folk Music', 90),
('Cruises', 100),
('C-pop', 42),
('Handball', 14),
('Chemistry', 59),
('Writing', 90),
('Skateboarding', 31),
('Australian rules football', 35),
('World news', 37),
('Auto racing', 8),
('Internet of things', 52),
('Tabletop gaming', 28),
('Table tennis', 30),
('Country music', 4),
('Art', 78),
('Cooking', 4),
('Writing', 63),
('Comedy', 11),
('Baseball', 72),
('Winter sports', 5),
('Popular franchises', 80),
('Augmented reality', 46),
('food Food', 21),
('technology Technology', 3),
('news Arts and culture news', 85),
('Investing', 6),
('Adventure travel', 2),
('Theme parks', 9),
('Video game platforms & hardware', 55),
('Information security', 60),
('Music news', 55),
('Basketball', 56),
('NCAA Women’s Basketball', 63),
('Fishing', 4),
('Databases', 25),
('Family', 45),
('Soft rock', 13),
('Alternative', 76),
('At home', 88),
('arts & culture', 7),
('Bollywood music', 74),
('Australian rules football', 4),
('Tabletop gaming', 50),
('Gaming news', 73),
('Metal', 81),
('Conservation & environmentalism', 95),
('Sailing', 49),
('Comics', 89),
('Music festivals', 89),
('Information security', 5),
('Gaming news', 17),
('Music news', 71),
('Motorcycle racing', 70),
('Sports news', 35),
('Video game platforms & hardware', 15),
('Sports journalists & coaches', 6),
('NBA', 53),
('Small business', 65),
('Fitness', 30),
('Archaeology', 10);
