insert into Topic (value) values 
('Handball'),
('Theme parks'),
('Soccer'),
('Video games'),
('Museums and institutions'),
('arts & culture'),
('Television'),
('Softball'),
('Skateboarding'),
('Collectibles'),
('Air travel'),
('Business & finance news'),
('Tech news'),
('Basketball'),
('NBA'),
('Anime'),
('Triathlon'),
('Internet of things'),
('Combat Sports'),
('Handball'),
('World music'),
('K-pop'),
('Folk Music'),
('music Music'),
('Music news'),
('Netball'),
('Investing'),
('Gaming news'),
('Bollywood music'),
('Gaming news'),
('Business & finance news'),
('Chefs'),
('Hockey'),
('Comics'),
('Astrology'),
('Gaming personalities & esports players'),
('Billiards'),
('Gaming news'),
('Business & finance news'),
('Australian rules football'),
('J-pop'),
('Social movements'),
('Gaming personalities & esports players'),
('Radio stations'),
('Soccer'),
('movies and tv Movies'),
('Marketing'),
('Sports icons'),
('Nature'),
('Cryptocurrencies'),
('Celebrities'),
('gaming Gaming'),
('Rock climbing'),
('entertainment Entertainment'),
('Celebrities'),
('Business & finance news'),
('Volleyball'),
('Martial arts'),
('Baseball'),
('Weather'),
('Winter sports'),
('Folk Music'),
('Australian Football League'),
('Tech personalities'),
('Rowing'),
('Comics'),
('Digital creators'),
('Music festivals'),
('Cloud computing'),
('Destinations'),
('Soft rock'),
('food Food'),
('At home'),
('Investing'),
('Esports'),
('Chefs'),
('Sports news'),
('Education'),
('Horoscope'),
('fashion & beauty Beauty'),
('K-hip hop'),
('Geography'),
('Entertainment brands'),
('Winter sports'),
('MLB'),
('Gaming personalities & esports players'),
('Theater'),
('National parks'),
('Punjabi music'),
('science Science'),
('Tennis'),
('NBA'),
('Football'),
('Dance'),
('Podcasts'),
('Golf'),
('Theme parks'),
('Nonprofits'),
('Sports news'),
('Education'),
('Experimental music'),
('C-pop'),
('Music news'),
('Martial arts'),
('Cycling'),
('Hip-hop & rap'),
('Chefs'),
('Rock'),
('Business professions'),
('Marketing'),
('Triathlon'),
('Basketball'),
('Anime'),
('hobbies & interests Animals'),
('Fishing'),
('Internet of things'),
('Basketball'),
('Drone technology'),
('Sports news'),
('US national news'),
('food Food'),
('Volleyball'),
('IndyCar'),
('World news'),
('Motorcycle racing'),
('Volleyball'),
('Luxury travel'),
('Motorcycle racing'),
('Electronic music'),
('Metal'),
('Nature'),
('Track & field'),
('Horse racing & equestrian'),
('Tabletop gaming'),
('Netball'),
('C-pop'),
('Pop'),
('Rugby'),
('Sci-fi and fantasy'),
('NCAA Women’s Basketball'),
('WNBA'),
('Destinations'),
('Handball'),
('Golf'),
('Chemistry'),
('Soft rock'),
('Small business'),
('Astrology'),
('entertainment Entertainment'),
('Space & astronomy'),
('Volleyball'),
('World news'),
('Indie spotlight'),
('Computer programming'),
('Business & finance news'),
('Sports news'),
('Books'),
('Small business'),
('At home'),
('music Music'),
('Rugby'),
('US national news'),
('Rowing'),
('Drone technology'),
('Indie spotlight'),
('Fishing'),
('Business & finance news'),
('Folk Music'),
('Gaming personalities & esports players'),
('Business & finance news'),
('Celebrities'),
('Golf'),
('Entertainment brands'),
('Rock'),
('Cricket'),
('Books'),
('Music brands'),
('Surfing'),
('Popular franchises'),
('Business travel'),
('Drone racing'),
('Electronic music'),
('Celebrities'),
('movies and tv Movies'),
('Business & finance news'),
('Museums and institutions'),
('Bollywood music'),
('Soccer'),
('Business & finance news'),
('Sci-fi and fantasy'),
('science Science'),
('Blues'),
('Esports'),
('Cheerleading'),
('Jazz'),
('Travel guides'),
('Cricket'),
('hobbies & interests Animals'),
('Darts'),
('NCAA Men’s Basketball'),
('Travel guides'),
('Folk Music'),
('Comics'),
('Australian Football League'),
('Air travel'),
('entertainment Entertainment'),
('Anime'),
('Local news'),
('Space & astronomy'),
('Family'),
('Internet of things'),
('J-pop'),
('Australian Football League'),
('Business & finance news'),
('Cloud platforms'),
('Health news'),
('Rock climbing'),
('Rugby'),
('Table tennis'),
('arts & culture'),
('Popular franchises'),
('Podcasts'),
('US national news'),
('Dance music'),
('Travel guides'),
('K-hip hop'),
('Rock'),
('R&B and soul'),
('Rugby'),
('Baseball'),
('Tech news'),
('Hockey'),
('Reggaeton'),
('Business & finance news'),
('Business & finance news'),
('Country music'),
('C-pop'),
('Transportation'),
('Cloud computing'),
('Business travel'),
('Golf'),
('Tech news'),
('Darts'),
('Cooking'),
('Horoscope'),
('entertainment Entertainment'),
('business & finance Business & finance'),
('news Arts and culture news'),
('Cricket'),
('Business professions'),
('Business professions'),
('Music festivals'),
('Game developers & publishers'),
('Business & finance news'),
('gaming Gaming'),
('outdoors Birdwatching'),
('Comics'),
('Radio stations'),
('Theme parks'),
('Fishing'),
('NCAA Men’s Basketball'),
('Skateboarding'),
('Theater'),
('Celebrities'),
('Basketball'),
('Theater'),
('Tech brands'),
('Internet of things'),
('Luxury travel'),
('Digital creators'),
('Video games'),
('Folk Music'),
('Gaming news'),
('Television'),
('Education'),
('Collectibles'),
('gaming Gaming'),
('Gaming news'),
('Astrology'),
('Music brands'),
('Musical instruments'),
('Cryptocurrencies'),
('Sports news'),
('food Food'),
('Adventure travel'),
('Transportation'),
('Australian rules football'),
('Museums and institutions'),
('Comics'),
('Swimming'),
('Musical instruments'),
('Punk'),
('Physics'),
('Indie spotlight'),
('Conservation & environmentalism'),
('Writing'),
('Virtual reality'),
('Drone technology'),
('COVID-19'),
('Geology'),
('movies and tv Movies'),
('Theme parks'),
('Music brands'),
('Business travel'),
('Investing'),
('K-hip hop'),
('Video games'),
('At home'),
('NASCAR'),
('Adventure travel'),
('Fashion'),
('Business travel'),
('Sports news'),
('Australian rules football'),
('Basketball'),
('Advertising'),
('Comedy'),
('Advertising'),
('arts & culture'),
('Fields of study'),
('Gaming personalities & esports players'),
('Sports journalists & coaches'),
('hobbies & interests Animals'),
('Geology'),
('Business personalities'),
('Entertainment brands'),
('sports Sports'),
('Tech brands'),
('arts & culture'),
('Punk'),
('Collectibles'),
('Radio stations'),
('news Arts and culture news'),
('Video games'),
('Basketball'),
('Business travel'),
('Internet of things'),
('Business personalities'),
('Archaeology'),
('Digital creators'),
('Softball'),
('Opera'),
('science Science'),
('Horoscope'),
('Theater'),
('Combat Sports'),
('Gaming news'),
('Celebrities'),
('Motorcycle racing'),
('R&B and soul'),
('Fishing'),
('Motorcycle racing'),
('Table tennis'),
('Gymnastics'),
('Comedy'),
('Digital creators'),
('National parks'),
('Collectibles'),
('Nature'),
('music Music'),
('Gaming news'),
('Sports journalists & coaches'),
('Science news'),
('Cooking'),
('National parks'),
('Tennis'),
('Popular franchises'),
('Auto racing'),
('Cloud computing'),
('Table tennis'),
('Softball'),
('Theater'),
('WNBA'),
('news Arts and culture news'),
('Rowing'),
('Gaming news'),
('Unexplained phenomena'),
('Sports news'),
('Music news'),
('sports Sports'),
('Unexplained phenomena'),
('Music festivals'),
('Theme parks'),
('Hunting'),
('Rodeo'),
('Investing'),
('National parks'),
('NBA'),
('Museums and institutions'),
('Virtual reality'),
('movies and tv Movies'),
('Volleyball'),
('Family'),
('At home'),
('movies and tv Movies'),
('Adventure travel'),
('Martial arts'),
('NCAA Women’s Basketball'),
('Tech news'),
('Netball'),
('NCAA Men’s Basketball'),
('Animation'),
('Business travel'),
('Business professions'),
('Weather'),
('Sailing'),
('Cheerleading'),
('National parks'),
('Softball'),
('outdoors Birdwatching'),
('Fantasy sports'),
('Darts'),
('Venture capital'),
('Reggaeton'),
('Chefs'),
('Small business'),
('J-pop'),
('Destinations'),
('Sports icons'),
('Cruises'),
('Archaeology'),
('Popular franchises'),
('Fields of study'),
('Sports news'),
('Tech news'),
('Radio stations'),
('Unexplained phenomena'),
('Track & field'),
('Luxury travel'),
('Triathlon'),
('Opera'),
('Tech news'),
('Comedy'),
('Rock'),
('Rock'),
('gaming Gaming'),
('Cycling'),
('Classic rock'),
('Australian rules football'),
('Rock'),
('Archaeology'),
('Country music'),
('Television'),
('movies and tv Movies'),
('Game developers & publishers'),
('Gaming news'),
('entertainment Entertainment'),
('Augmented reality'),
('Business professions'),
('Theater'),
('technology Technology'),
('Australian rules football'),
('Tech news'),
('Comics'),
('Advertising'),
('Cloud platforms'),
('Football'),
('Sports journalists & coaches'),
('Astrology'),
('outdoors Birdwatching'),
('K-pop'),
('outdoors Birdwatching'),
('Tabletop gaming'),
('Alternative'),
('World news'),
('gaming Gaming'),
('Surfing'),
('Rodeo'),
('arts & culture'),
('Science news'),
('Destinations'),
('Business travel'),
('Hip-hop & rap'),
('technology Technology'),
('Science news'),
('Gymnastics'),
('Destinations'),
('Cloud computing'),
('Track & field'),
('Comedy'),
('Sports icons'),
('gaming Gaming'),
('Celebrities'),
('Tech personalities'),
('Cryptocurrencies'),
('Winter sports'),
('Sports icons'),
('Hockey'),
('Softball'),
('Augmented reality'),
('Chemistry'),
('Indie spotlight'),
('entertainment Entertainment'),
('Winter sports'),
('Television'),
('Social movements'),
('Archaeology'),
('Classical music'),
('Fantasy sports'),
('Dance'),
('Golf'),
('Jazz'),
('Tech brands'),
('Music festivals'),
('Tech news'),
('Information security'),
('Chemistry'),
('Chemistry'),
('Drone technology'),
('Fields of study'),
('NCAA Women’s Basketball'),
('Geography'),
('movies and tv Movies'),
('Classic rock'),
('Track & field'),
('Soft rock'),
('fashion & beauty Beauty'),
('Alternative'),
('Bollywood music'),
('news Arts and culture news'),
('NCAA Men’s Basketball'),
('Science news'),
('Hip-hop & rap'),
('Television'),
('WNBA'),
('R&B and soul'),
('Surfing'),
('Rugby'),
('Internet of things'),
('Business travel'),
('Drone technology'),
('Music festivals'),
('Transportation'),
('Cricket'),
('Folk Music'),
('careers Accounting'),
('Blues'),
('Theme parks'),
('Tabletop gaming'),
('Winter sports'),
('Music festivals'),
('Motorcycle racing'),
('arts & culture'),
('At home'),
('Fantasy sports'),
('Swimming'),
('Sports news'),
('Education'),
('Indie spotlight'),
('Music festivals'),
('Science news'),
('Music news'),
('Cooking'),
('fashion & beauty Beauty'),
('Virtual reality'),
('Collectibles'),
('outdoors Birdwatching'),
('Biology'),
('Tennis'),
('Business & finance news'),
('Fitness'),
('Cryptocurrencies'),
('Nonprofits'),
('Rock'),
('Sports journalists & coaches'),
('Space & astronomy'),
('Virtual reality'),
('MLB'),
('news Arts and culture news'),
('R&B and soul'),
('Advertising'),
('Cryptocurrencies'),
('Dance'),
('At home'),
('Cricket'),
('Swimming'),
('Chefs'),
('Swimming'),
('Science news'),
('COVID-19'),
('Experimental music'),
('FinTech'),
('Venture capital'),
('Rock climbing'),
('Cooking'),
('Netball'),
('Tennis'),
('Destinations'),
('news Arts and culture news'),
('Auto racing'),
('Hockey'),
('Esports'),
('Game developers & publishers'),
('Comedy'),
('Handball'),
('Folk Music'),
('Gaming news'),
('music Music'),
('Chemistry'),
('Musical instruments'),
('Billiards'),
('sports Sports'),
('Rowing'),
('C-pop'),
('Billiards'),
('Video game platforms & hardware'),
('travel Travel'),
('sports Sports'),
('Venture capital'),
('Australian rules football'),
('National parks'),
('Pop'),
('Cycling'),
('Australian rules football'),
('technology Technology'),
('Destinations'),
('Esports'),
('Track & field'),
('Science news'),
('Gaming personalities & esports players'),
('Cryptocurrencies'),
('Netball'),
('Sports icons'),
('Music festivals'),
('Softball'),
('Chefs'),
('Art'),
('Gaming news'),
('Venture capital'),
('Dance'),
('Collectibles'),
('Skateboarding'),
('NASCAR'),
('Netball'),
('Cryptocurrencies'),
('outdoors Birdwatching'),
('Comedy'),
('Hunting'),
('NCAA Women’s Basketball'),
('Sports icons'),
('Billiards'),
('science Science'),
('Dance'),
('Handball'),
('Startups'),
('Classic rock'),
('movies and tv Movies'),
('Baseball'),
('Table tennis'),
('Sports news'),
('Air travel'),
('Rowing'),
('Anime'),
('business & finance Business & finance'),
('business & finance Business & finance'),
('Combat Sports'),
('Movie news'),
('Small business'),
('Weather'),
('Table tennis'),
('outdoors Birdwatching'),
('Internet of things'),
('Dance music'),
('Punjabi music'),
('Gaming news'),
('Podcasts'),
('Cruises'),
('Adventure travel'),
('Blues'),
('Art'),
('Hunting'),
('NBA'),
('Geology'),
('Computer programming'),
('Cricket'),
('Entertainment brands'),
('Tech news'),
('MLB'),
('Local news'),
('K-pop'),
('Swimming'),
('Tabletop gaming'),
('news Arts and culture news'),
('Cryptocurrencies'),
('news Arts and culture news'),
('Biology'),
('Netball'),
('Classical music'),
('National parks'),
('Classic rock'),
('outdoors Birdwatching'),
('K-pop'),
('Virtual reality'),
('Hockey'),
('Cricket'),
('Databases'),
('Business travel'),
('Track & field'),
('Bollywood music'),
('Skateboarding'),
('Horoscope'),
('Fitness'),
('Dance music'),
('World news'),
('Winter sports'),
('Tech brands'),
('Business & finance news'),
('Gaming news'),
('arts & culture'),
('sports Sports'),
('Adventure travel'),
('Cloud computing'),
('IndyCar'),
('FinTech'),
('Soft rock'),
('news Arts and culture news'),
('Local news'),
('Archaeology'),
('Lacrosse'),
('Cricket'),
('Handball'),
('K-pop'),
('Fitness'),
('Advertising'),
('Dance music'),
('Lacrosse'),
('Sci-fi and fantasy'),
('FinTech'),
('Small business'),
('IndyCar'),
('Musical instruments'),
('Basketball'),
('Travel guides'),
('FinTech'),
('Classic rock'),
('Horse racing & equestrian'),
('Martial arts'),
('FinTech'),
('Information security'),
('Luxury travel'),
('Horoscope'),
('Music brands'),
('Adventure travel'),
('Folk Music'),
('Nonprofits'),
('Nature'),
('Music news'),
('Astrology'),
('Winter sports'),
('Music news'),
('Augmented reality'),
('sports Sports'),
('WNBA'),
('Internet of things'),
('Sports icons'),
('Chemistry'),
('Podcasts'),
('Sports news'),
('technology Technology'),
('Cryptocurrencies'),
('Drone technology'),
('C-pop'),
('Dance'),
('business & finance Business & finance'),
('Sports news'),
('Football'),
('Football'),
('Information security'),
('MLB'),
('Chemistry'),
('Cloud computing'),
('Formula 1'),
('Business & finance news'),
('Investing'),
('Venture capital'),
('arts & culture'),
('Motorcycle racing'),
('Theme parks'),
('FinTech'),
('Drone racing'),
('Science news'),
('Blues'),
('Reggaeton'),
('Computer programming'),
('COVID-19'),
('Music festivals'),
('Hip-hop & rap'),
('Transportation'),
('food Food'),
('Cryptocurrencies'),
('FinTech'),
('Punk'),
('Tech news'),
('Video game platforms & hardware'),
('gaming Gaming'),
('Science news'),
('C-pop'),
('Sailing'),
('Music festivals'),
('Cooking'),
('Archaeology'),
('NASCAR'),
('Hip-hop & rap'),
('Museums and institutions'),
('Track & field'),
('Classic rock'),
('Popular franchises'),
('Volleyball'),
('Musical instruments'),
('Radio stations'),
('Health news'),
('Martial arts'),
('Gymnastics'),
('Celebrities'),
('Health news'),
('news Arts and culture news'),
('Gaming personalities & esports players'),
('Anime'),
('National parks'),
('Marketing'),
('Local news'),
('Experimental music'),
('Sports journalists & coaches'),
('IndyCar'),
('arts & culture'),
('Social movements'),
('Startups'),
('NCAA Women’s Basketball'),
('Cloud computing'),
('Jazz'),
('Horse racing & equestrian'),
('Rodeo'),
('Volleyball'),
('Art'),
('Game developers & publishers'),
('Baseball'),
('K-pop'),
('Music news'),
('sports Sports'),
('Volleyball'),
('Tech news'),
('IndyCar'),
('Blues'),
('food Food'),
('Books'),
('Opera'),
('FinTech'),
('Local news'),
('Musical instruments'),
('Handball'),
('Astrology'),
('Theme parks'),
('At home'),
('Netball'),
('J-pop'),
('FinTech'),
('Nature'),
('Conservation & environmentalism'),
('Fields of study'),
('Music festivals'),
('Music news'),
('Collectibles'),
('Information security'),
('Motorcycle racing'),
('Radio stations'),
('food Food'),
('Combat Sports'),
('Social movements'),
('Gymnastics'),
('Rugby'),
('IndyCar'),
('Darts'),
('FinTech'),
('Internet of things'),
('FinTech'),
('Archaeology'),
('music Music'),
('Gaming news'),
('Basketball'),
('technology Technology'),
('Australian rules football'),
('Metal'),
('careers Accounting'),
('NCAA Women’s Basketball'),
('Dance music'),
('Chemistry'),
('Fields of study'),
('NCAA Men’s Basketball'),
('Virtual reality'),
('Business travel'),
('Rock climbing'),
('Pop'),
('Space & astronomy'),
('Horse racing & equestrian'),
('Chefs'),
('Nonprofits'),
('Australian rules football'),
('Cycling'),
('Adventure travel'),
('sports Sports'),
('Dance'),
('Music brands'),
('Esports'),
('Cloud computing'),
('Soccer'),
('Music brands'),
('Classic rock'),
('Blues'),
('Esports'),
('Hip-hop & rap'),
('At home'),
('Business & finance news'),
('Hockey'),
('NCAA Men’s Basketball'),
('Swimming'),
('Drone technology'),
('Video game platforms & hardware'),
('Music news'),
('Gaming personalities & esports players'),
('J-pop'),
('Formula 1'),
('Opera'),
('Hockey'),
('Cycling'),
('Music news'),
('Sports news'),
('Esports'),
('Venture capital'),
('Punjabi music'),
('Popular franchises'),
('Horse racing & equestrian'),
('Bollywood music'),
('food Food'),
('Folk Music'),
('Social movements'),
('Horoscope'),
('Dance'),
('Gaming news'),
('Animation'),
('World news'),
('Combat Sports'),
('Anime'),
('Geography'),
('fashion & beauty Beauty'),
('music Music'),
('Digital creators'),
('Fantasy sports'),
('Celebrities'),
('Esports'),
('Comics'),
('Hockey'),
('Astrology'),
('Collectibles'),
('Gaming personalities & esports players'),
('Country music'),
('Science news'),
('Luxury travel'),
('Physics'),
('fashion & beauty Beauty'),
('Family'),
('Lacrosse'),
('Unexplained phenomena'),
('Dance'),
('Tech news'),
('Basketball'),
('entertainment Entertainment'),
('Reggaeton'),
('At home'),
('Alternative'),
('Astrology'),
('US national news'),
('Cricket'),
('Fitness'),
('Netball'),
('Cloud computing'),
('Indie spotlight'),
('Sports news'),
('Physics'),
('Business personalities'),
('movies and tv Movies'),
('Popular franchises'),
('Collectibles'),
('Geography'),
('Netball'),
('Small business'),
('US national news'),
('Sports news'),
('Family'),
('Dance music'),
('Information security'),
('Motorcycle racing'),
('Cryptocurrencies'),
('Cloud computing'),
('Soft rock'),
('NBA'),
('Horse racing & equestrian'),
('business & finance Business & finance'),
('Science news'),
('Business travel'),
('Tabletop gaming');
